services:
  hyperparameter-optimizer:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount results directory for persistence
      - ./optimization_results:/app/optimization_results
      # Mount datasets directory if you have local datasets
      - ./datasets:/app/datasets
      # Mount logs directory for debugging
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - TZ=Asia/Bangkok
    # GPU support (uncomment for RunPod/GPU environments)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    # Restart policy
    restart: unless-stopped
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s